import type { GalleryImage } from '@/types/content';

// Photos from public/images/galeries/ (provided by the client, 2026-10-01).
// 19.jpg is a byte-identical duplicate of 1.jpg, so it is not listed.
// width/height are the real file dimensions, used for the full-size image in the modal.
export const gallery: GalleryImage[] = [
  {
    id: 'g-01',
    src: '/images/galeries/1.jpg',
    width: 700,
    height: 699,
    alt: 'Roofer fastening underlayment on a residential roof deck',
  },
  {
    id: 'g-02',
    src: '/images/galeries/2.jpg',
    width: 700,
    height: 699,
    alt: 'Roofer carrying materials during a roof tear-off next to a brick wall',
  },
  {
    id: 'g-03',
    src: '/images/galeries/3.jpg',
    width: 1200,
    height: 1200,
    alt: 'Aerial view of a large home with a brown asphalt shingle roof',
  },
  {
    id: 'g-04',
    src: '/images/galeries/4.jpg',
    width: 2000,
    height: 1332,
    alt: 'Aerial view of a brown shingle roof surrounded by trees',
  },
  {
    id: 'g-05',
    src: '/images/galeries/5.png',
    width: 932,
    height: 815,
    alt: 'Gray shingle roof ridge overlooking a residential neighborhood',
  },
  {
    id: 'g-06',
    src: '/images/galeries/6.png',
    width: 932,
    height: 815,
    alt: 'Flat commercial roof with skylights',
  },
  {
    id: 'g-07',
    src: '/images/galeries/7.jpg',
    width: 2000,
    height: 1332,
    alt: 'Completed asphalt shingle roof installation',
  },
  {
    id: 'g-08',
    src: '/images/galeries/8.jpeg',
    width: 465,
    height: 465,
    alt: 'Close-up of hands installing asphalt shingles',
  },
  {
    id: 'g-09',
    src: '/images/galeries/9.jpeg',
    width: 393,
    height: 393,
    alt: 'Close-up of a lifted and damaged asphalt shingle',
  },
  {
    id: 'g-10',
    src: '/images/galeries/10.jpeg',
    width: 407,
    height: 407,
    alt: 'Roofer installing a flat roof membrane at dusk',
  },
  {
    id: 'g-11',
    src: '/images/galeries/11.jpeg',
    width: 474,
    height: 474,
    alt: 'Close-up of a curled and weathered asphalt shingle edge',
  },
  {
    id: 'g-12',
    src: '/images/galeries/12.jpeg',
    width: 1000,
    height: 666,
    alt: 'Roofer in a safety harness installing metal roofing panels',
  },
  {
    id: 'g-13',
    src: '/images/galeries/13.png',
    width: 1536,
    height: 1024,
    alt: 'Tree branch overhanging a shingle roof with debris in the gutter',
  },
  {
    id: 'g-14',
    src: '/images/galeries/14.png',
    width: 1536,
    height: 1024,
    alt: 'Close-up of warped and uneven asphalt shingles',
  },
  {
    id: 'g-15',
    src: '/images/galeries/15.png',
    width: 1536,
    height: 1024,
    alt: 'Collage of six roofing materials: shingle, metal, clay tile, wood shake, slate, and composite',
  },
  {
    id: 'g-16',
    src: '/images/galeries/16.jpg',
    width: 2000,
    height: 1332,
    alt: 'Close-up of an asphalt shingle roof',
  },
  {
    id: 'g-17',
    src: '/images/galeries/17.jpg',
    width: 1600,
    height: 1067,
    alt: 'Weathered stone-style roof above white walls and flower boxes',
  },
  {
    id: 'g-18',
    src: '/images/galeries/18.jpg',
    width: 2000,
    height: 1125,
    alt: 'Brown asphalt shingle roof with several hips against a blue sky',
  },
  {
    id: 'g-20',
    src: '/images/galeries/20.jpg',
    width: 787,
    height: 787,
    alt: 'Aerial view of a new home under construction with a dark shingle roof',
  },
  {
    id: 'g-21',
    src: '/images/galeries/21.jpeg',
    width: 700,
    height: 700,
    alt: 'Roofer installing asphalt shingles with a nail gun',
  },
  {
    id: 'g-22',
    src: '/images/galeries/22.jpg',
    width: 1400,
    height: 787,
    alt: 'Aerial view of a house foundation at a construction site',
  },
];
