import type { Review } from '@/types/content';

// Google reviews, copied manually from the Google Business Profile on 2026-09-30.
// No API integration. Do not write, merge, or edit review text.
// Google only shows relative dates ("3 years ago"), so `date` is the estimated year
// until the client provides the export with exact dates — see docs/06-pertanyaan-terbuka.md #11.
// Star-only reviews (no text) are not included.
export const reviews: Review[] = [
  {
    id: 'r-001',
    author: 'Donna Meade',
    date: '2026',
    rating: 5,
    text: 'I highly recommend Rick and his team . Their work is excellent . Ricks service is outstanding. Every time I called him he got right back to me\nOther roofing companies would take a few days or longer. Very happy 😊',
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-002',
    author: 'Margo Magness',
    date: '2026',
    rating: 5,
    text: "Great company--great customer service!  I couldn't be happier with my new roof---the price was reasonable, the crew was polite and helpful and worked hard, they finished on time and left my property clean. I highly recommend them",
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-003',
    author: 'Kenneth Lewis',
    date: '2025',
    rating: 5,
    text: 'Your crew & team were very efficient,  professional & thorough,  I was amazed! The service & honesty that you brought was a key factor in going forward with Canyon Construction.  Thank you for delivering as promised.  I would & will recommend to anyone needing this type of work.  I love  my new roofing!',
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-004',
    author: 'Carol Cintron',
    date: '2025',
    rating: 5,
    text: 'Canyon Construction replaced my roof in a professional and timely manner.  They replaced it on-time and in budget.  All this while I was still living out of state.  If I ever need a roof again or if anyone every asks me I would recommend Canyon Construction without any hesitation or reservation.  Bottom line - if you need a new roof, Call Rick at Canyon Construction!',
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-005',
    author: 'Antonio Gallegos',
    date: '2025',
    rating: 5,
    text: 'We are thrilled with the new roof!! The end results gave our house a great refresh. Working with Rick made it easy to accomplish the requirements from our insurance carrier and he was flexible with our schedule. We would easily recommend.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-006',
    author: 'Joel Garrison',
    date: '2024',
    rating: 5,
    text: 'Rick and his crew are absolutely ROCK STARS! From the start, Rick made everything so easy for my wife and I.We had numerous quotes from different companies and his price was the best in town. Ricks crew showed up and were completely done with everything in a day and a half! The roof looks amazing! I will be recommending Canyon Construction to anyone and everyone that needs any roofing done! Thank you Rick and your crew!',
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-007',
    author: 'Shawn Robinson',
    date: '2024',
    rating: 5,
    text: 'A great company that does amazing work! I couldn’t be happier! A big project and complete in 2 days can’t even tell they were here!!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-008',
    author: 'Kimberly Youth Association',
    date: '2024',
    rating: 5,
    text: 'Rick and his expert crews are always great to work with! They ride quality materials, excellent communicators and get the job done fast!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-009',
    author: 'Christa Whitmore',
    date: '2024',
    rating: 5,
    text: "Canyon did the roof for my Mom's house.  They did an excellent job! They got the job done quickly and did an excellent job of cleaning up before they left.\nHighly recommended!",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-010',
    author: 'Janet Jensen',
    date: '2024',
    rating: 1,
    text: 'We had a new roof put on in August and it was leaking by January! Rick refuses to fix or repair the the problems areas (which there ended up being three in total). We found him Untrustworthy, only after a buck in the end. He promised many things to be done prior to the start of the project, all of which did not get done, but at the very least I would expect a roof that didn’t leak!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-011',
    author: 'anthony scampini',
    date: '2024',
    rating: 5,
    text: 'Professional and honest service. Full roof replacement on an older home, work finished in a day and a half with excellent quality. Highly recommend.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-012',
    author: 'Kenneth Carpenter',
    date: '2024',
    rating: 5,
    text: "It doesn't  get any better than the quick    professional  service",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-013',
    author: 'Robert A.',
    date: '2023',
    rating: 5,
    text: 'As new residents to this area, we did not know who to turn to for the new roof we needed back in 2021. Canyon Construction Services (CCS) was the first call we made. Rick instilled total trust and confidence in his company\'s abilities to provide us with superior workmanship and quality. In 2023, we had an issue with a small roof leak at the flashing/chimney area. I shared this with Rick and he was right on it! He came out with a crew of 4 people and they repaired the problem "good as new" in a very timely manner. There was no charge at all for the quality warranty work that was provided. He did not let us down! We highly recommend CCS for any roofing project/repair you may have.',
    source: 'Google',
    city: null,
    featured: true,
  },
  {
    id: 'r-014',
    author: 'scott burt',
    date: '2023',
    rating: 5,
    text: 'Simple, straight forward transaction with no gimmicky sales pitches. The work was done quickly with no problems. They were one of the lower estimates acquired and the estimate was unmodified when it came time for payment. They are a Malarkey recommended installer, and were able to register/certify a warranty through Malarkey. I would recommend them if you have the unfortunate need to reroof your own home.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-015',
    author: 'Phil McCaslin',
    date: '2023',
    rating: 5,
    text: 'Needed to replace roof for insurance purposes. Contacted 4 roofing companies and only 2 responded, one of which was Canyon Construction. As Canyon was lowest bid I contacted to have the job done. After speaking with them on the phone I knew I made the right choice. Very informative and professional. Job took 2 days which was expected, cleanup was great. Kudos to the roofers for such excellent work.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-016',
    author: 'Baldemar Gonzalez',
    date: '2023',
    rating: 5,
    text: 'Very professional and responsive!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-017',
    author: 'Steve Rosengreen',
    date: '2022',
    rating: 5,
    text: 'Canyon Construction did an excellent job at replacing our old cedar shake roof. Rick is very personable & his crew friendly also. Job wasn’t scheduled to start until early June but he we able to start much earlier & finished it up in 2 days. Wife is very happy with the experience. Would highly recommend if you need a new roof.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-018',
    author: 'Jody Busman',
    date: '2022',
    rating: 5,
    text: 'Work was excellent and done in 1 day. Other roofs in my neighborhood took 5-7 days. Their were 5 men on the job and they cleaned up everything beautifully. Highly recommend. Respectful and excellent customer service',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-019',
    author: 'Missy',
    date: '2022',
    rating: 5,
    text: "I'm so Happy that we found Canyon Construction services. They were professional and fast to help fix our roof.",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-020',
    author: 'Dallas Jenks',
    date: '2022',
    rating: 5,
    text: 'Price seemed quit fair and they did a great job for us.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-021',
    author: 'lisa j',
    date: '2021',
    rating: 5,
    text: "As new residents to this area, we did not know who to turn to for the new roof we needed. Canyon Construction Services (CCS) was the first call we made. Rick instilled total trust and confidence in his company's abilities to provide us with superior workmanship and quality. He did not let us down! We highly recommend CCS for any roofing project/repair you may have.",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-022',
    author: 'Tyler & Jen Christensen',
    date: '2021',
    rating: 5,
    text: 'Canyon Construction did an awesome job with our roof replacement! They were very flexible and easy to work with. Highly recommend!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-023',
    author: 'Zarina Umarova',
    date: '2021',
    rating: 5,
    text: 'Rick and his team have done a great job on replacing our roof. Very responsive , honest and professional team!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-024',
    author: 'David Harris',
    date: '2020',
    rating: 5,
    text: 'Rick and Becky are quite the team... Friendly, professional, responsive, and genuine.  Came in as the best price, promised plenty and delivered more.  Hardest working site crew you can imagine.  Cupertino, ("Coop") the project supervisor is personable, accommodating and responsive to any concerns or suggestions you might have.  Cleaned up at the end of each day and left the job spotless.  On time, on budget, no surprises... Canyon Construction Services LLC receives my highest recommendation.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-025',
    author: 'Nola Montgomery',
    date: '2020',
    rating: 5,
    text: "Absolutely without question we'd recommend Canyon Construction Services. Owners Rick & Rebecca provided us with great information on roofing alternatives so that we could make an informed decision on what type of re-roofing system was best for our home. Pricing was very competitive. The removal of the existing roof started on a Monday morning and by the following Wednesday evening all required structural repairs were completed and our new roof was 100% installed.",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-026',
    author: 'Betty Zimmerman',
    date: '2020',
    rating: 5,
    text: 'We are very happy with the completed reroofing of our home.  The crew from Canyon Construction Services was professional, on time, efficient, and hard working.  Several neighbors have commented on the finished look of our new roof and have asked for business cards (we asked the owners to please leave a few for us to distribute). We also appreciate the prompt and professional communication the owners provided. We highly recommend this business for your reroofing needs.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-027',
    author: "Shannon O'Toole",
    date: '2020',
    rating: 5,
    text: "Rick and his team just finished my roof and I couldn't be more impressed with the job they completed.  I would recommend them for any roofing job.  All the team members were friendly and they cleaned up everyday.",
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-028',
    author: 'Tamie Sudik',
    date: '2020',
    rating: 5,
    text: 'Rick with Canyon Construction Services is the best of the best! He went above and beyond for me with multiple homes he has done roofing services for! I would highly recommend him and his staff!!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-029',
    author: 'Carla Bicart',
    date: '2020',
    rating: 5,
    text: 'Showed up on time and got the job done when they said they would. Very responsive to my inquiries and concerns. Provided a great value on our roofing and used quality materials. Also very friendly and easy to work with!',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-030',
    author: 'Jason Brown',
    date: '2020',
    rating: 5,
    text: 'Canyon Construction did a very good job. They came in and helped us replace our roof after moving into a new home.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-031',
    author: 'Bob Bailey',
    date: '2020',
    rating: 5,
    text: 'Fast friendly and efficient service. Did a great job at a great price. Highly recommended.',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-032',
    author: 'Brent Howard',
    date: '2020',
    rating: 5,
    text: 'Excellent company. OnPoint on time and reasonably priced',
    source: 'Google',
    city: null,
    featured: false,
  },
  {
    id: 'r-033',
    author: 'Robert Kinghorn',
    date: '2020',
    rating: 5,
    text: 'Hard working professional crew\nLoved the results',
    source: 'Google',
    city: null,
    featured: false,
  },
];
